set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "catppuccin/tmux#v2.1.3"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Reload tmux config
unbind r
bind r source-file ~/.tmux.conf
set -g prefix C-a

# Bind window splitting
unbind % 
unbind '"'

# performance stuff
set -g history-limit 50000
set -g mouse on
set -g focus-events on
set -g repeat-time 100

# splits open in the current pane’s dir
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# split window resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Vim-like copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle

# Default shell
set-option -g default-shell /usr/bin/zsh

# shell naming
set -g allow-rename off
set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command}'

# Terminal settings
set -g allow-passthrough on
set-option -sg escape-time 10
set-option -sa terminal-overrides ',alacritty:RGB'

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# key bit: use the window name (#W) in tabs
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Keep at bottom
run ~/.tmux/plugins/tpm/tpm
